### ISSUE TITLE
HTTPS/WSS Messenger Client to HTTP/WS Messenger Server

### ISSUE THREAD

**Issue by skylerknecht** [skylerknecht/messenger#2]
When a TLS-enabled Messenger Client requests to connect to a non-TLS-enabled Messenger Server a nasty error is thrown. Let's find a way to catch this error.

```
Traceback (most recent call last):
  File "/Users/skylerknecht/Documents/Repositories/messenger/venv/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x03'
      ^
Error handling request
Traceback (most recent call last):
  File "/Users/skylerknecht/Documents/Repositories/messenger/venv/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x03'
      ^
```

**Comment by skylerknecht** [comment]
Closed because we moved it to https://github.com/skylerknecht/messenger/issues/3
